service: stoneChallenge

custom:
  dotenv:
    path: .env

plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-dotenv-plugin
  - serverless-offline

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    ENV: ${env:ENV}
    REGION: ${env:REGION}
    TABLE_NAME: ${env:TABLE_NAME}
    SECRET: ${env:SECRET}
    DYNAMO_ENDPOINT: ${env:DYNAMO_ENDPOINT}
    COUNT_KEY: ${env:COUNT_KEY}
    COUNT_ACCESS_URL: ${env:COUNT_ACCESS_URL}
    INCREASE_COUNT_ACCESS_URL: ${env:INCREASE_COUNT_ACCESS_URL}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:PutItem
        - dynamodb:ListStreams
        - dynamodb:DescribeStream

      Resource: "*"

functions:
  signupFunction:
    handler: src/index.signupFunction
    events:
      - http:
          path: /v1/signup
          method: post
  addAccessCountFunction:
    handler: src/index.addAccessCountFunction
    events:
      - http:
          path: /v1/count
          method: get
  userInfoFunction:
    handler: src/index.userInfoFunction
    events:
      - http:
          path: /v1/info/{email}
          method: get
  increaseAccessCountFunction:
    handler: src/index.increaseAccessCountFunction
    events:
      - http:
          path: /v1/increase
          method: get


